# Generated by Django 5.2.7 on 2025-11-12 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('bonus', models.IntegerField()),
                ('demotion', models.IntegerField()),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='air.user')),
            ],
        ),
    ]
