# Generated by Django 5.2.7 on 2025-11-12 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='air.employee')),
            ],
            bases=('air.employee',),
        ),
        migrations.CreateModel(
            name='Deliverer',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='air.employee')),
            ],
            bases=('air.employee',),
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warnings', models.PositiveIntegerField()),
                ('balance', models.PositiveIntegerField()),
                ('vip', models.BooleanField()),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air.user')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air.chef')),
            ],
        ),
        migrations.CreateModel(
            name='DishRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air.dish')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='air.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=256)),
                ('when', models.DateTimeField()),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air.user')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air.thread')),
            ],
        ),
        migrations.CreateModel(
            name='Compliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air.user')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air.message')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('v', 'valid'), ('p', 'pending'), ('i', 'invalid')], max_length=1)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air.user')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air.message')),
            ],
        ),
    ]
