# Generated by Django 6.0 on 2025-12-10 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0002_chef_deliverer_dish_order_thread_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishrating',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dishrating',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air.dish'),
        ),
    ]
