# Generated by Django 5.2.7 on 2025-11-12 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0002_chef_deliverer_thread_customer_dish_dishrating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('v', 'valid'), ('p', 'pending'), ('i', 'invalid')], default='pending', max_length=1),
        ),
        migrations.CreateModel(
            name='OrderedDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('dish', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='air.dish')),
                ('from_order_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air.order')),
            ],
        ),
    ]
