# Generated by Django 5.2.7 on 2025-11-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0003_order_alter_complaint_status_ordereddish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='img',
            field=models.CharField(default='?', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('CU', 'Customer'), ('DL', 'Deliverer'), ('CH', 'Chef'), ('MN', 'Manager')], default='CU', max_length=2),
        ),
        migrations.AlterField(
            model_name='thread',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
