# Generated by Django 6.0 on 2025-12-10 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0003_dishrating_id_alter_dishrating_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='air.customer'),
        ),
        migrations.AlterField(
            model_name='ordereddish',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air.dish'),
        ),
        migrations.AlterField(
            model_name='ordereddish',
            name='from_order_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='air.order'),
        ),
    ]
