# Generated by Django 5.2.7 on 2025-11-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0004_dish_img_user_type_alter_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='sender',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='compliment',
            name='sender',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='to',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='compliment',
            name='to',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
