# Generated by Django 5.2.7 on 2025-11-25 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0005_complaint_sender_compliment_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ComplaintSender', to='air.user'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ComplaintTo', to='air.user'),
        ),
        migrations.AlterField(
            model_name='compliment',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ComplimentSender', to='air.user'),
        ),
        migrations.AlterField(
            model_name='compliment',
            name='to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ComplimentTo', to='air.user'),
        ),
    ]
