# Generated by Django 6.0 on 2025-12-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0009_faqentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('FD', 'Fired'), ('OK', 'Okay'), ('PR', 'Promoted'), ('DM', 'Demoted')], default='OK', max_length=2),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('v', 'valid'), ('p', 'pending'), ('i', 'invalid')], default='p', max_length=1),
        ),
    ]
