# Generated by Django 6.0 on 2025-12-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0010_employee_status_alter_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('FD', 'Fired'), ('OK', 'Okay'), ('WR', 'Warned'), ('PR', 'Promoted'), ('DM', 'Demoted')], default='OK', max_length=2),
        ),
    ]
