# Generated by Django 6.0 on 2025-12-11 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0014_order_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('deleted', 'Deleted'), ('kept', 'Kept')], default='pending', max_length=10)),
                ('faq_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air.faqentry')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
    ]
