# Generated by Django 6.0 on 2025-12-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0015_reportedfaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vip_exclusive',
            field=models.BooleanField(default=False),
        ),
    ]
